import { Injectable, BadRequestException, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../../common/database/prisma.service';

@Injectable()
export class StaffSchedulesService {
    constructor(private readonly prisma: PrismaService) { }

    async getAvailableOpenings(currentUser: any, weekStartDate: string) {
        const startDate = new Date(weekStartDate);

        // PT employees explore published plans for their department
        const plan = await this.prisma.deptWeeklyPlan.findUnique({
            where: {
                departmentId_weekStartDate: {
                    departmentId: currentUser.departmentId,
                    weekStartDate: startDate,
                },
                status: 'PUBLISHED',
            },
        });

        if (!plan) return [];

        // Return openings enabled for PT with remaining capacity
        const openings = await this.prisma.shiftOpening.findMany({
            where: {
                planId: plan.id,
                isPTEnabled: true
            },
            include: {
                template: { select: { name: true, code: true } }
            },
            orderBy: { date: 'asc' }
        });

        // Calculate remaining capacity
        return openings.map(opening => ({
            ...opening,
            remainingCapacity: opening.ptCapacity - opening.ptRegistered,
            templateName: opening.template?.name
        }));
    }

    async registerShift(currentUser: any, openingId: string) {
        if (currentUser.employmentType !== 'PART_TIME') {
            throw new BadRequestException('Chỉ nhân viên Part-time mới được đăng ký ca');
        }

        // Use transaction to ensure capacity integrity
        return this.prisma.$transaction(async (tx) => {
            const opening = await tx.shiftOpening.findUnique({
                where: { id: openingId },
                include: { plan: true }
            });

            if (!opening || opening.plan.status !== 'PUBLISHED') {
                throw new NotFoundException('Shift is not available');
            }

            if (!opening.isPTEnabled) {
                throw new BadRequestException('This shift is not open for Part-time employees');
            }

            // 1. Check capacity
            if (opening.ptRegistered >= opening.ptCapacity) {
                throw new BadRequestException('This shift is full');
            }

            // 2. Check if user already has a shift on this date
            const existingUserShift = await tx.shift.findFirst({
                where: {
                    employeeId: currentUser.id,
                    date: opening.date
                }
            });

            if (existingUserShift) {
                throw new BadRequestException('You already have a shift on this date');
            }

            // 3. Check weekly limit (5 shifts for PT)
            const weekShifts = await tx.shift.count({
                where: {
                    employeeId: currentUser.id,
                    schedule: { weekStartDate: opening.plan.weekStartDate }
                }
            });

            if (weekShifts >= 5) {
                throw new BadRequestException('You have reached the maximum of 5 shifts for this week');
            }

            // 4. Update opening registration count atomically
            await tx.shiftOpening.update({
                where: { id: openingId },
                data: { ptRegistered: { increment: 1 } }
            });

            // 5. Create or Get WorkSchedule
            const schedule = await tx.workSchedule.upsert({
                where: {
                    employeeId_weekStartDate: {
                        employeeId: currentUser.id,
                        weekStartDate: opening.plan.weekStartDate
                    }
                },
                update: {}, // Keep existing status if exists
                create: {
                    employeeId: currentUser.id,
                    weekStartDate: opening.plan.weekStartDate,
                    status: 'PENDING'
                }
            });

            // 6. Create the Shift
            return tx.shift.create({
                data: {
                    scheduleId: schedule.id,
                    employeeId: currentUser.id,
                    openingId: opening.id,
                    date: opening.date,
                    shiftType: opening.shiftType,
                    startTime: opening.startTime,
                    endTime: opening.endTime,
                    isAutoGenerated: false,
                    notes: 'Đăng ký bởi nhân viên Part-time'
                }
            });
        });
    }

    async getMySchedules(currentUser: any) {
        return this.prisma.workSchedule.findMany({
            where: { employeeId: currentUser.id },
            include: {
                shifts: {
                    orderBy: { date: 'asc' }
                }
            },
            orderBy: { weekStartDate: 'desc' }
        });
    }
}
