export enum ScheduleStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  LOCKED = 'LOCKED',
  REJECTED = 'REJECTED'
}

export enum PlanStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  LOCKED = 'LOCKED'
}

export enum ShiftType {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
  EVENING = 'EVENING',
  NIGHT = 'NIGHT'
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY'
}

export interface Shift {
  id: string;
  scheduleId: string;
  employeeId: string;
  employee?: {
    id: string;
    fullName: string;
    email: string;
    employmentType?: string; // FULL_TIME or PART_TIME
  };
  openingId?: string; // Link to shift opening
  date: string; // ISO date string
  shiftType: ShiftType;
  startTime: string; // HH:mm format
  endTime: string; // HH:mm format
  isAutoGenerated: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface WorkSchedule {
  id: string;
  weekStartDate: string; // ISO date string (Monday)
  employeeId: string;
  employee?: {
    id: string;
    fullName: string;
    email: string;
    employmentType: string;
    department?: {
      id: string;
      name: string;
    };
  };
  submittedAt: string;
  status: ScheduleStatus;
  approvedById?: string;
  approvedBy?: {
    id: string;
    fullName: string;
  };
  approvedAt?: string;
  lockedAt?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  shifts?: Shift[];
}

export interface CreateScheduleDto {
  weekStartDate: string; // ISO date string (Monday)
  employeeId: string;
  notes?: string;
  shifts: CreateShiftDto[];
}

export interface CreateShiftDto {
  date: string; // ISO date string
  shiftType: ShiftType;
  startTime: string; // HH:mm
  endTime: string; // HH:mm
  notes?: string;
}

export interface UpdateScheduleDto {
  status?: ScheduleStatus;
  notes?: string;
  approvedById?: string;
}

export interface ScheduleFilterDto {
  status?: ScheduleStatus;
  employeeId?: string;
  departmentId?: string;
  weekStartDate?: string;
  startDate?: string;
  endDate?: string;
}

// ============================================
// DEPT WEEKLY PLAN & SHIFT OPENING
// ============================================

export interface ShiftOpening {
  id: string;
  planId: string;
  templateId?: string;
  template?: {
    id: string;
    name: string;
    code: string;
  };
  date: string;
  shiftType: ShiftType;
  startTime: string;
  endTime: string;

  // FT Capacity
  isFTEnabled: boolean;
  // NOTE: ftAutoAssigned đã bị loại bỏ - không còn auto-assign logic

  // PT Capacity (renamed for consistency with backend)
  isPTEnabled: boolean;        // allowRegister in UI
  ptCapacity: number;          // maxEmployee in UI
  ptRegistered: number;

  notes?: string;
  createdAt?: string;
  updatedAt?: string;

  // Employee assignments
  shifts?: Shift[];

  // Helpers (computed in UI)
  remainingCapacity?: number;
  templateName?: string;
}

export interface DeptWeeklyPlan {
  id: string;
  departmentId: string;
  department?: {
    id: string;
    name: string;
    code: string;
  };
  weekStartDate: string;
  status: PlanStatus;
  createdByUserId?: string;
  createdAt: string;
  updatedAt: string;
  shiftOpenings?: ShiftOpening[];
}

export interface CreateWeeklyPlanDto {
  weekStartDate: string;
  notes?: string;
}

// Helper to convert ShiftOpening ptCapacity <-> maxEmployee for UI
export function shiftOpeningToUI(opening: ShiftOpening) {
  return {
    ...opening,
    maxEmployee: opening.ptCapacity,
    allowRegister: opening.isPTEnabled,
    remainingCapacity: opening.ptCapacity - opening.ptRegistered
  };
}

export function shiftOpeningFromUI(data: any): Partial<ShiftOpening> {
  return {
    ...data,
    ptCapacity: data.maxEmployee,
    isPTEnabled: data.allowRegister
  };
}
